// <auto-generated />
namespace GalaxyShoes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class shoes5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shoes5));
        
        string IMigrationMetadata.Id
        {
            get { return "201911212042508_shoes5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
